### ISSUE TITLE
Self update deployer error

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/mirage-ci#28]
The self update deployment fails with this builds error:
```
2023-02-10 01:26.02: Exec: "docker" "build" "-f" "/tmp/git-checkout4d10508/Dockerfile" 
                           "--iidfile" "/tmp/git-checkout4d10508/docker-iid" 
                           "--" "/tmp/git-checkout4d10508"
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
2023-02-10 01:26.02: Job failed: Docker build exited with status 1
```

I've switched off the self update since the deployment is already handled by ocurrent-deployer here https://deploy.ci3.ocamllabs.io/?repo=ocurrent/mirage-ci&

**Comment by TheLortex** [comment]
Now that it's managed by ocurrent-deployer the self-update logic should be removed from the code

**Comment by tmcgilchrist** [comment]
I have a fix for it but if we don't really need it. I'll remove it.
