### ISSUE TITLE
maintenance -- vendored things, and code documentation

### ISSUE THREAD

**Issue by hannesm** [ocurrent/mirage-ci#38]
hey,

I finally discovered this repository, and it's a bit unclear to me why there are so many things in `vendor` that seem to be released as well.

another question: what and in which configuration is this service deployed (where?)?

**Comment by samoht** [comment]
I've started to remove vendored code here: #39 

Here also a first draft of the documentation: https://hackmd.io/rSCkkWEcQ9agi6p39t3rRw @TheLortex can you check that I didn't wrote any mistake? @hannesm is it helpful? What kind of information do you want to see in there? Once in a proper state, I'll push the doc to the repo.

**Comment by TheLortex** [comment]
I have added two comments but overall it looks good. Thank you for writing this

**Comment by tmcgilchrist** [comment]
It would be worth describing the GitHub App used for delivering web hooks and how that triggers builds. Otherwise that document looks good.

**Comment by hannesm** [comment]
Thanks for writing that documentation. I still lack some information:
- which are the optons the `ocurrent-deployer` uses to launch mirage-ci? (is this relevant? I'd guess some `--test-mirage4` to be present?
- your document mentions various repositories that are "watched" -- how does this mechanism work? likely there's some other documentation already covering it, just point to it
- while I worked in #37, I didn't understand how "mirage-ci" figures out when and which pipelines to trigger for a PR.

Maybe you can start with an overview of the setup, i.e. which systems / repositories are involved for the CI to work (from my understanding, there's "ocurrent-deployer", somewhere something about this GitHub application (sending noitifications to mirage-ci?), and this repository itself.

And maybe state where this CI (and whether both or a single pipeline) is executed on a PR (such as opam-overlays? mirage? mirage-skeleton?).

I'd as well appreciate documentation about the "friend PR" in the README hereof -- from my experience, it means the main descripton of a PR needs to include the line "To test with: <link to PR of mirage-skeleton / mirage>" (but of course I may be wrong)?

**Comment by hannesm** [comment]
Whatever it takes, it seems others are happy with this thing here. Closing.
