### ISSUE TITLE
Yet another confusion - please sync branches and update the base

### ISSUE THREAD

**Issue by hannesm** [ocurrent/mirage-ci#46]
So, the `live` and the `main` branch diverge. Would it be possible to make them even?

And, while looking into this, can we upgrade from the arcane debian-10 images to something more up to date (and also to a OCaml 4.14 compiler)?

Thanks a lot for your work on this project :D

**Comment by mtelvers** [comment]
The branches are now in sync.  https://github.com/ocurrent/mirage-ci/pull/45 has updated to Debian 12 and 4.14.  Thus this issue looks to be resolved.
